/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlackSection: typeof import('./src/components/Landing/component/BlackSection.vue')['default']
    BP_Home: typeof import('./src/components/Landing/views/BP_Home.vue')['default']
    Carroucel: typeof import('./src/components/Landing/component/Carroucel.vue')['default']
    Carrousel_Left: typeof import('./src/components/About_component/Carrousel_Left.vue')['default']
    Carrousel_Right: typeof import('./src/components/About_component/Carrousel_Right.vue')['default']
    ChessboardGallery: typeof import('./src/components/Landing/component/ChessboardGallery.vue')['default']
    Cursor_Follower: typeof import('./src/components/Cursor_Follower.vue')['default']
    Curved_Carroucel: typeof import('./src/components/Curved_Carroucel.vue')['default']
    First: typeof import('./src/components/About_component/First.vue')['default']
    For: typeof import('./src/components/Expertise_Component/for.vue')['default']
    Forth: typeof import('./src/components/About_component/Forth.vue')['default']
    Gsap3dPositionV1: typeof import('./src/components/gsap-3d-position-v1.vue')['default']
    Hero_section: typeof import('./src/components/Carriere_Component/Hero_section.vue')['default']
    Image_Forme: typeof import('./src/components/Image_Forme.vue')['default']
    Loader: typeof import('./src/components/Landing/component/loader.vue')['default']
    Marque_Carrousel: typeof import('./src/components/Landing/component/Marque_Carrousel.vue')['default']
    Motion: typeof import('motion-v')['Motion']
    NavBar_Component: typeof import('./src/components/NavBar/NavBar_Component.vue')['default']
    One_Component: typeof import('./src/components/Expertise_Component/one_Component.vue')['default']
    page: typeof import('./src/components/About_component/Pieds de page.vue')['default']
    'Pieds de page': typeof import('./src/components/About_component/Pieds de page.vue')['default']
    Profile_Squad: typeof import('./src/components/Profile_Squad.vue')['default']
    Profile_Squad_2: typeof import('./src/components/Profile_Squad_2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Second: typeof import('./src/components/About_component/Second.vue')['default']
    Test_Component: typeof import('./src/components/Test_Component.vue')['default']
    'TestProfilView[1]': typeof import('./src/components/About_component/TestProfilView[1].vue')['default']
    Three: typeof import('./src/components/About_component/Three.vue')['default']
    Three_Component: typeof import('./src/components/Expertise_Component/three_Component.vue')['default']
    Two_Component: typeof import('./src/components/Expertise_Component/two_Component.vue')['default']
    VideoSection: typeof import('./src/components/Landing/component/VideoSection.vue')['default']
  }
}
